"""Add cover image to Release

Revision ID: 136f815fe1d2
Revises: 93093e980c31
Create Date: 2025-09-22 11:57:12.207216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '136f815fe1d2'
down_revision = '93093e980c31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('releases', schema=None) as batch_op:
        batch_op.drop_column('cover_image_url')

    # ### end Alembic commands ###
