"""Add delivery_date to orders

Revision ID: 20af0f388b28
Revises: a5af9a4e75f5
Create Date: 2025-12-14 22:06:36.798905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20af0f388b28'
down_revision = 'a5af9a4e75f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shipping_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('delivery_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('delivery_date')
        batch_op.drop_column('comment')
        batch_op.drop_column('shipping_address')

    with op.batch_alter_table('bands', schema=None) as batch_op:
        batch_op.drop_column('cover_image_url')

    # ### end Alembic commands ###
