"""dd role to ustomer model

Revision ID: 375455e42c75
Revises: 84b2c47cd47e
Create Date: 2025-09-15 18:09:43.256677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '375455e42c75'
down_revision = '84b2c47cd47e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
