"""Change duration to Integer in Composition

Revision ID: a5af9a4e75f5
Revises: 136f815fe1d2
Create Date: 2025-09-22 18:59:29.937138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5af9a4e75f5'
down_revision = '136f815fe1d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compositions', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.TIME(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('compositions', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.Integer(),
               type_=sa.TIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
