"""Add phone_number to customer_profiles

Revision ID: c3d96e47bbdd
Revises: 20af0f388b28
Create Date: 2025-12-15 09:59:32.987237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d96e47bbdd'
down_revision = '20af0f388b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer_profiles', schema=None) as batch_op:
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###
